version: '3.8'

services:
  backend:
    build:
      context: ./standalone-backend
      dockerfile: Dockerfile
    container_name: mumantij_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - /tmp/mumantij:/tmp
